server:
  port: 9002

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost
    
management:
  endpoint:
    health:
      show-details: always