spring:
  devtools:
    livereload:
      enabled: false
  profiles:
    active: 'local'
  application:
    name: 'school-service'
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: xe
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    #database-platform: 'org.hibernate.dialect.H2Dialect'
    database-platform: 'org.hibernate.dialect.Oracle10gDialect'
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    graphiql:
      enabled: true